name: .NET CI with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'  # Specify your required .NET version

    - name: Install dependencies
      run: dotnet restore SonarIntegration/SonarIntegration.csproj

    - name: Build
      run: dotnet build SonarIntegration/SonarIntegration.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SonarIntegration/SonarIntegration.csproj --configuration Release --no-build --logger:trx

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: SonarQube Scan
      run: |
        dotnet tool install --global dotnet-sonarscanner
        export PATH="$PATH:/home/runner/.dotnet/tools"
        dotnet sonarscanner begin /k:"sonarintegration" /d:sonar.host.url="${{ env.SONAR_HOST_URL }}" /d:sonar.login="${{ env.SONAR_TOKEN }}"
        dotnet build SonarIntegration/SonarIntegration.csproj --configuration Release
        dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: |
          **/*.trx
